spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vet
    username: postgres
    password: 5171

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true

  thymeleaf:
    cache: false