spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vet
    username: postgres
    password: 5171

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false