spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vet
    username: postgres
    password: 5171

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true

  thymeleaf:
    cache: false